[package]
authors = ["Cristian Cobzarenco <cristi.cobzarenco@gmail.com>"]
name = "rs_doom"
version = "0.0.9"

[[bin]]
name = "rs_doom"

[dependencies]
wad = { path = "wad" }
engine = { path = "engine" }
game = { path = "game" }
math = { path = "math" }

clap = "2.32.0"
env_logger = "0.5.12"
error-chain = "0.12.0"
time = "0.1.35"

[dependencies.log]
features = ["release_max_level_info"]
version = "0.4.3"

[workspace]

