[package]
authors = ["Cristi Cobzarenco <cristi.cobzarenco@gmail.com>"]
name = "engine"
version = "0.1.0"
edition = "2018"

[dependencies]
error-chain = "0.12.0"
glium-typed-buffer-any = "0.4.0"
idcontain = "0.7.5"
num-traits = "0.2.5"
rusttype = "0.7.5"
unicode-normalization = "0.1.7"

[dependencies.log]
features = ["release_max_level_info"]
version = "0.4.3"

[dependencies.math]
path = "../math"

[dependencies.glium]
features = ["glutin"]
version = "0.23.0"

[dev-dependencies]
env_logger = "*"
